services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/dist
      - node_modules_backend:/app/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/dist
      - node_modules_frontend:/app/node_modules

volumes:
  node_modules_backend: {}
  node_modules_frontend: {}
